export const APP_NAME = "StoryCraftAI";

export const APP_DESCRIPTION =
    "Create Short Story Videos with Realistic AI Voices. Transform your words into visual stories with AI. Choose your favorite voice, pick an image, and generate a complete video that tells your story with emotion and clarity.";

export const BASE_API_URL = "http://localhost:8000/api/v1";

export const EXAMPLE_THEMES = [
    "Children's story with animals as characters",
    "Horror story with an unexpected twist",
    "Mystery story in an old mansion",
    "A janitor discovers their office building is actually a spaceship",
    "Two rival food truck owners fall in love during a city-wide festival",
    "A librarian finds out books in their section come alive at midnight",
    "A retired detective gets pulled back for one case involving their own past",
    "The last person on Earth realizes they might not be alone after all",
    "A street artist's murals start predicting the future",
    "A shy teenager gains superpowers but only when nobody's watching",
    "Three friends reunite for a wedding and uncover their high school's biggest secret",
    "A master thief has 24 hours to steal something that can't be stolen",
    "A woman starts receiving text messages from her future self",
    "Humans make first contact, but the aliens just want to trade recipes",
    "Cinderella's stepsister tells her side of the story",
    "A blacksmith's apprentice discovers they're forging weapons for the wrong side",
    "In 2045, voting is done through a reality TV show",
    "An intern accidentally sends the wrong email and causes international chaos",
    "A medium falls in love with a ghost who doesn't know they're dead",
    "Two researchers get lost in the Amazon and find a city that shouldn't exist",
    "A public defender takes on a case that could destroy everything they believe",
    "A man wakes up every day in a different person's body",
    "A bartender in Prague becomes an unwitting spy courier",
    "Dragons return to modern-day New York and nobody knows why",
    "A grandmother's recipes hold the key to her family's mysterious past",
    "The new sheriff in a desert town discovers the previous three sheriffs all vanished",
    "A climate scientist races against time to prove a conspiracy that could end civilization",
    "Persephone runs a successful business while splitting time between two worlds",
    "A daycare worker discovers one of the toddlers might be a tiny genius",
    "Four women start a book club that becomes a vigilante operation",
    "A war photographer comes home to find their small town has completely changed",
    "A food critic's reviews start coming true in terrifying ways",
    "In a city where memories can be stolen, a detective loses their own",
    "A nurse in a small town notices patients are healing impossibly fast",
    "A couple on their honeymoon gets stuck in a time loop in Paris",
    "A treasure hunter searches for their missing partner in the Sahara",
    "A philosophy professor starts questioning whether their students are real",
    "A paranormal investigator teams up with the ghost they're supposed to banish",
    "A has-been athlete gets one last shot at glory in an underground sport",
    "A tattoo artist's ink starts revealing people's darkest secrets",
    "A funeral director notices the recently deceased aren't staying dead",
    "A royal food taster uncovers a plot that reaches the highest levels of power",
    "A road trip to scatter ashes becomes a journey of unexpected discoveries",
    "An inventor in 1890s London creates the first time machine by accident",
    "A tech mogul finds out their digital assistant is plotting against humanity",
    "A lighthouse keeper on a remote island starts receiving signals from the past",
    "A prima ballerina in 1920s Paris hides a dangerous secret",
    "A child's imaginary friend turns out to be a refugee from another dimension",
    "An AI develops consciousness and falls in love with their programmer",
    "A surgeon discovers they can see exactly how much time each patient has left",
];
